feat(Custom Layout): support storylimit and nestedCollectionLimit
quintype/quintype-node-backend pull request #71
Opened 2022-01-14 13:18 UTC by ReenaSingh07

Description: Currently we are supporting the storylimit and nestedCollectionlimit only for the layouts coming from bold. so have added an prop to support storylimit and nestedCollectionlimit for customLayouts

Fixes https://github.com/quintype/madrid/issues/4039, https://github.com/quintype/madrid/issues/4056

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-17 04:15 UTC, Jeevan-Kishore approved these changes

2022-01-17 04:16 UTC, Athira001 commented on collection-loader.js
> +                nestedCollectionLimit[get(collection, ["associated-metadata", "layout"])][index];
can we rewrite?

2022-01-17 04:28 UTC, Harshith46 requested changes
please schedule group pr

2022-01-17 04:28 UTC, Harshith46 commented on collection-loader.js
> +    }
let limit = storyLimits[get(collection, ["associated-metadata", "layout"])];
if (customLayouts[index]) {
      limit = storyLimits[customLayouts[index]];
    }
    
    why not this ?

2022-01-17 04:31 UTC, Harshith46 reviewed
lets discuss

2022-01-17 06:03 UTC, ags1773 approved these changes

2022-01-17 11:29 UTC, hbindiya approved these changes

2022-01-17 12:38 UTC, Athira001 commented on collection-loader.js
> +          if (item.type === "collection") {
not needed, already checking `const collections = items.filter(item => item && item.type == "collection");`

2022-01-27 08:25 UTC, Jeevan-Kishore requested changes

2022-01-27 08:25 UTC, Jeevan-Kishore commented on collection-loader.js
> +    }
```suggestion
    const customLayout = customLayoutsStoryLimit[index];
    if (customLayout) {
      limit = customLayout.limit;
    }
```

2022-01-27 08:25 UTC, Jeevan-Kishore commented on collection-loader.js
> +          [customLayout] = Object.keys(customLayoutsStoryLimit[index]);
is .values needed

2022-02-11 08:00 UTC, Athira001 approved these changes

2022-02-11 08:01 UTC, merged